"""Telegram message formatting helpers."""

from __future__ import annotations


def format_number(n: int) -> str:
    """Format number with K/M suffix: 12345 → '12.3K'."""
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n / 1_000:.1f}K"
    return str(n)


def trend_emoji(trend: str) -> str:
    return {"up": "📈", "down": "📉", "stable": "➡️"}.get(trend, "")


def urgency_emoji(urgency: str) -> str:
    return {"now": "🔴", "upcoming": "🟡", "plan_ahead": "🟢"}.get(urgency, "⚪")


def format_gap_insight(gap: dict, rank: int) -> str:
    """Format a single gap insight for Telegram."""
    trend = trend_emoji(gap.get("trend", ""))
    examples = gap.get("example_videos", [])
    examples_text = ""
    if examples:
        examples_text = "\n".join(f"     • {t}" for t in examples[:2])
        examples_text = f"\n   Examples:\n{examples_text}"

    return (
        f"*{rank}. {gap['topic']}* {trend}\n"
        f"   Score: {gap['score']} | Avg views: {format_number(gap['avg_views'])}\n"
        f"   Competitors: {gap['competitor_videos']} videos | You: {gap['your_videos']} videos"
        f"{examples_text}"
    )


def format_brief(niche_name: str, gaps: list[dict], alerts: list[dict]) -> str:
    """Format a daily briefing message."""
    lines = [f"🔍 *Daily Brief — {niche_name}*\n"]

    if gaps:
        lines.append("📊 *Top Content Gaps:*")
        for i, gap in enumerate(gaps[:3], 1):
            lines.append(format_gap_insight(gap, i))
        lines.append("")

    if alerts:
        lines.append("⚡ *Competitor Activity:*")
        for alert in alerts[:5]:
            lines.append(f"  {alert['message']}")
        lines.append("")

    if not gaps and not alerts:
        lines.append("Nothing notable today — your niche is quiet. ✌️")

    lines.append(f"_Generated by NicheScope_")
    return "\n".join(lines)


def format_competitor_report(insight: dict) -> str:
    """Format a competitor deep-dive for Telegram."""
    lines = [
        f"🎯 *Competitor Report: {insight['channel_title']}*",
        f"   @{insight['handle']} | {format_number(insight['subscriber_count'])} subs\n",
        f"📹 *Last 7 days:* {insight['videos_posted_7d']} videos, "
        f"{format_number(insight['total_views_7d'])} total views\n",
        "*Recent videos:*",
    ]

    for v in insight.get("recent_videos", [])[:5]:
        lines.append(
            f"  • {v['title']}\n"
            f"    {format_number(v['views'])} views | "
            f"{v['views_per_day']}/day | [Watch]({v['url']})"
        )

    if insight.get("top_topic"):
        lines.append(f"\n🏷️ *Top topic:* {insight['top_topic']}")

    return "\n".join(lines)


# ---------- Forward-Looking Feature Formatters ----------


def format_demands(niche_name: str, clusters) -> str:
    """Format demand mining results for Telegram."""
    lines = [f"💬 *Audience Demands — {niche_name}*\n"]
    lines.append("_What your audience is literally ASKING for:_\n")

    if not clusters:
        lines.append("No demand signals found yet. Need more competitor data.")
        return "\n".join(lines)

    for i, c in enumerate(clusters[:8], 1):
        lines.append(
            f"*{i}. {c.topic}*\n"
            f"   📊 {c.request_count} requests | 👍 {c.total_likes} likes | "
            f"Strength: {c.strength_score}\n"
            f"   📺 From: {', '.join(c.source_channels[:3])}"
        )
        if c.example_requests:
            lines.append(f"   💬 _{c.example_requests[0][:80]}..._")
        lines.append("")

    lines.append("_💡 These are real viewer requests from competitor comments._")
    return "\n".join(lines)


def format_calendar(niche_name: str, entries) -> str:
    """Format seasonal content calendar for Telegram."""
    lines = [f"📅 *Content Calendar — {niche_name}*\n"]
    lines.append("_Publish BEFORE the peak to ride the wave:_\n")

    if not entries:
        lines.append("No seasonal patterns detected yet. Need more historical data.")
        return "\n".join(lines)

    for entry in entries:
        urg = urgency_emoji(entry.urgency)
        lines.append(
            f"{urg} *{entry.topic_label}*\n"
            f"   📆 Publish: {entry.recommended_publish_window}\n"
            f"   📈 Peak: {entry.peak_month} ({entry.peak_multiplier:.1f}x baseline)\n"
            f"   💡 _{entry.reason}_"
        )
        lines.append("")

    lines.append("🔴 = Act now  🟡 = Coming soon  🟢 = Plan ahead")
    return "\n".join(lines)


def format_collabs(niche_name: str, opps) -> str:
    """Format collaboration opportunities for Telegram."""
    lines = [f"🤝 *Collab Opportunities — {niche_name}*\n"]
    lines.append("_High relevance × low audience overlap = maximum growth:_\n")

    if not opps:
        lines.append("No collaboration data yet. Need more competitor channels.")
        return "\n".join(lines)

    for i, o in enumerate(opps[:5], 1):
        overlap_bar = {"low": "🟢 Low", "medium": "🟡 Medium", "high": "🔴 High"}
        lines.append(
            f"*{i}. {o.channel_title}* (@{o.handle})\n"
            f"   👥 {format_number(o.subscriber_count)} subs | "
            f"Overlap: {overlap_bar.get(o.audience_overlap_estimate, o.audience_overlap_estimate)}\n"
            f"   🎯 Topic match: {o.topic_overlap_score:.0%} | "
            f"🚀 Potential reach: ~{format_number(o.potential_reach)} new viewers"
        )
        if o.shared_topics:
            lines.append(f"   🏷️ Shared: {', '.join(o.shared_topics[:4])}")
        if o.existing_collabs:
            lines.append(f"   🔗 Already {o.existing_collabs} collabs detected")
        lines.append("")

    lines.append("_💡 Best partners: similar topics, different audiences._")
    return "\n".join(lines)


def format_format_insights(niche_name: str, insights) -> str:
    """Format format intelligence results for Telegram."""
    lines = [f"🎬 *Format Intelligence — {niche_name}*\n"]
    lines.append("_It's not just WHAT you make — it's HOW:_\n")

    if not insights:
        lines.append("Not enough data to analyze formats. Need more videos per topic.")
        return "\n".join(lines)

    for i, ins in enumerate(insights[:8], 1):
        lines.append(
            f"*{i}. {ins.topic_label}*\n"
            f"   ✅ Best: *{ins.best_format}* ({ins.best_duration}) → "
            f"{format_number(ins.best_avg_views)} avg views\n"
            f"   ❌ Worst: {ins.worst_format} → "
            f"{format_number(ins.worst_avg_views)} avg views\n"
            f"   📊 *{ins.multiplier}x difference*"
        )
        lines.append("")

    lines.append("_💡 Match the winning format to multiply your views._")
    return "\n".join(lines)


def format_title_scores(niche_name: str, scores) -> str:
    """Format title scoring results for Telegram."""
    lines = [f"🏆 *Title Scorer — {niche_name}*\n"]

    if not scores:
        lines.append("No titles to score.")
        return "\n".join(lines)

    for i, s in enumerate(scores, 1):
        medal = {1: "🥇", 2: "🥈", 3: "🥉"}.get(i, f"#{i}")
        lines.append(f"{medal} *{s.title}*")
        lines.append(f"   Score: *{s.score}/100*")

        if s.strengths:
            for strength in s.strengths[:3]:
                lines.append(f"   {strength}")

        if s.weaknesses:
            for weakness in s.weaknesses[:2]:
                lines.append(f"   {weakness}")

        if s.suggestions:
            for suggestion in s.suggestions[:2]:
                lines.append(f"   {suggestion}")

        lines.append("")

    if len(scores) > 1:
        winner = scores[0]
        lines.append(f"🎯 *Recommendation:* Go with _{winner.title}_ (score: {winner.score})")

    return "\n".join(lines)
